### ISSUE TITLE
[NEED HELP] Need your help, @michaelvillar!

### ISSUE THREAD

**Issue by dalisoft** [michaelvillar/dynamics.js#10]
Hi @michaelvillar 
I used matrix compose/decompose from you dynamics.js, and my tweening engine is another type. All works fine, including IE9, also gets all current style back to IE9!
But in all browser rotateZ doesn't work properly, i seen in your demo site all works fine, please help.
* I will keep dynamics.js link in tweening engine my source used list

Sorry for my english

**Comment by michaelvillar** [comment]
Do you have more information? This seems too vague for me to help.

**Comment by dalisoft** [comment]
http://codepen.io/anon/pen/yNpvpg - Demo. 45/90deg working, but 180, 360deg not working, scaling. Thank you for reply. My tweening engine is Animo.js, have timeScale, restart, seek, play, pause and more like GSAP features.
DynamicsJS i seen, best work, high-performance

**Comment by olegomon** [comment]
Hi @michaelvillar 
do you have any plans to add methods to reverse a running animation?

**Comment by dalisoft** [comment]
Hi @olegomon !
Exactly for what feature you using DynamicsJS?

**Comment by michaelvillar** [comment]
@olegomon probably not, you can do it yourself and call the reverse animation in the complete callback though.
