### ISSUE TITLE
Weird Issue Animating Object Propery

### ISSUE THREAD

**Issue by JohnLouderback** [michaelvillar/dynamics.js#11]
I have the following code:
![dynamicsweirdness1](https://cloud.githubusercontent.com/assets/4743179/8509476/7c4c02ea-225a-11e5-9f4c-e0a793b3699a.PNG)
which, should, in theory, animate the ``zoom`` property on the ``Camera`` object to the specified value. However, the behavior I'm seeing is very strange where only the first few frames animate and then it spends the rest of the duration setting the value to the end value:
![dynamicsweirdness2](https://cloud.githubusercontent.com/assets/4743179/8509480/c2bffa88-225a-11e5-98a7-579d7ab77a9c.PNG)
This seems like a bug, but if perhaps I'm doing this incorrectly, please let me know.

**Comment by michaelvillar** [comment]
Where's the Camera object from? Some library like Threejs?

**Comment by JohnLouderback** [comment]
It's custom code I've written, the source of which is written in TypeScript.

Here's the TypeScript code:
```typescript
class Camera {
	public static x: number = 0;
	public static y: number = 0;
	private static _zoom: number = 1;
	public static get zoom(): number {
		return Camera._zoom;
	}
	public static set zoom(value) {
		Camera._zoom = value;
		StatusBar.editorZoomStatus.text = StatusBar.editorZoomText;
		console.log('zoom now = ' + value);
	}
}
```
which in turn is compiled to:
```javascript
var Camera = (function () {
    function Camera() {
    }
    Object.defineProperty(Camera, "zoom", {
        get: function () {
            return Camera._zoom;
        },
        set: function (value) {
            Camera._zoom = value;
            StatusBar.editorZoomStatus.text = StatusBar.editorZoomText;
            console.log('zoom now = ' + value);
        },
        enumerable: true,
        configurable: true
    });
    Camera.x = 0;
    Camera.y = 0;
    Camera._zoom = 1;
    return Camera;
})();
```

**Comment by JohnLouderback** [comment]
Any news on this?

**Comment by michaelvillar** [comment]
Sorry, just seeing this now.
I'm not sure setter/getter is supported, I'd assumed it would but maybe if it doesn't work it comes from that?

**Comment by michaelvillar** [comment]
After a further look at this, this seems unrelated to dynamics
