### ISSUE TITLE
Inconsistent `dynamics.stop()`

### ISSUE THREAD

**Issue by stavro** [michaelvillar/dynamics.js#16]
Calling `dynamics.stop()` doesn't work for certain animation types.

Demonstration:

![dynamics](https://cloud.githubusercontent.com/assets/2391584/11170660/a8ae5e52-8b8f-11e5-8190-c31cbfa9d5a9.gif)

http://codepen.io/anon/pen/GpzoYV

**Comment by stavro** [comment]
I believe this has to do with having a `delay` added.  I would expect `stop` to stop upcoming animations even if there was a delay set in the animation parameters.

**Comment by michaelvillar** [comment]
Hey, you're right. This is a bug when multiple delayed animations are pending. 

Just fixed it here: https://github.com/michaelvillar/dynamics.js/commit/b2c039763cc5cb6dc44c08623a5ea99414f04b62

**Comment by stavro** [comment]
Thanks @michaelvillar!
