### ISSUE TITLE
Some strange error occured 

### ISSUE THREAD

**Issue by fobdy** [michaelvillar/dynamics.js#17]
I've been writing some tests and got some error occured in karma test Chrome environment.

```javascript
var $elem = document.querySelector('.message');
dynamics.animate($elem, {
    scale: 1.5
  }, {
    type: dynamics.bounce,
    frequency: 450,
    friction: 200,
    duration: 1000
})
```

Will raise following error in karma Chrome:

```javascript
Uncaught TypeError: Cannot read property '0' of undefined
    DecomposedMatrix.interpolate @ index.js:17591
    __bind @ index.js:16817
    interpolate @ index.js:18198
    animationTick @ index.js:18181
    runLoopTick @ index.js:18149
```
It fails on the following line [src/dynamics.coffee#L495](https://github.com/michaelvillar/dynamics.js/blob/master/src/dynamics.coffee#L495)
```javascript
decomposed[k][i] = (decomposedB[k][i] - decomposedA[k][i]) * t + decomposedA[k][i];
```
I've dived into code and find that it's because `decomposedB.transform` is `false`, so `decomposedB['transform'][0]` cannot be evaulated.

The `decomposedB` is set to `false` in `startAnimation` with following line:
```javascript
endProperties['transform'] = matrix.decompose(); 
```

matrix is created with
```javascript
matrix = Matrix.fromTransform(Matrix.matrixForTransform(v));
```

`v` is `"scaleX(1.5) scaleY(1.5) scaleZ(1.5)"`

And later `matrix.decompose()` returns `false` because of this statement:

```javascript
if (els[3][3] === 0) {
  return false;
}
```

So if this is normal, then problem with some if statement in `for` cycle:

```coffeescript
if !only? or only.indexOf(k) > -1 or only.indexOf("#{k}#{['x','y','z'][i]}") > -1
```

In original non karma environment everything works fine, but few conditions is not the same.

**Comment by michaelvillar** [comment]
I never used Karma before, can you tell me the steps to reproduce?

**Comment by fobdy** [comment]
Ok, i'll try to compose some minimal demo

**Comment by michaelvillar** [comment]
Thank you!

**Comment by michaelvillar** [comment]
Ping!

**Comment by fobdy** [comment]
Ok, sorry. I'll try to replay this on newer versions of karma & chrome

**Comment by michaelvillar** [comment]
Please reopen this if you give more information ;)
