### ISSUE TITLE
add support for css filters

### ISSUE THREAD

**Issue by kilianc** [michaelvillar/dynamics.js#27]
Unless I missed the part in the docs that mentions how to interpolate custom props or how to handle filters.

**Comment by michaelvillar** [comment]
You should be able to do so. dynamics interpolate strings too :)

**Comment by kilianc** [comment]
yo @michaelvillar link to an example? 

simply doing `filter: blur(20px)` didn't work :/

**Comment by michaelvillar** [comment]
Here's an working example: https://gist.github.com/michaelvillar/fe9cfb41058293cffa62e117f13760d3
The trick is to se the `filter` to `blur(0px)` as the initial state. Dynamics doesn't work really well when default values aren't set, I should do this better.
