### ISSUE TITLE
Integrating with React

### ISSUE THREAD

**Issue by aitoroses** [michaelvillar/dynamics.js#6]
Hi Michael,
I liked so much ```dynamics.js``` and i've been playing around with it for a while.

I have been trying to implement an integration with React and I think I found a pretty easy and smart way to do it.

You should really check this out from my gist!

This could be the next Famo.us ;)

[React and Dynamics integration concept](https://gist.github.com/aitoroses/e9b3d77b637fc6ad9087)

**Comment by michaelvillar** [comment]
That seems pretty cool. I'm not sure it's the best way since I'm not really familiar with React! I hope people can find this issue if they want to play with it on React. Will close for now since it's not really an issue :)
