### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by xjiaoyang** [michaelvillar/dynamics.js#7]
some advices:
1: add samples to repo not just on website page
2: add some tests to codepen
3: integrate with angularjs/reactjs or any popular FE projects.

**Comment by michaelvillar** [comment]
1: why exactly? I like keeping the repo clean. Maybe in another one but I'm not sure of the goal.
2: tell me more
3: I don't plan to do that, but some people might want to do it :) (react: https://github.com/michaelvillar/dynamics.js/issues/6)

**Comment by Qinwroks** [comment]
1: if i clone the repo then i will have a get-start usage/instruction file
2: for testing、writing a tutorial、embed your CodePen demos on home page.
3: maybe i can submit a PR on angularjs later

**Comment by chinnichaitanya** [comment]
Integration with AngularJS is useful for many developers.

**Comment by pepe** [comment]
I am actually fine with the idea of clean repo and demo page (especially if it is prominently shown in the readme).

My 2 cents thou.

**Comment by GilianAbels** [comment]
AngularJS is fantastic!
