### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by chinnichaitanya** [michaelvillar/dynamics.js#8]
This will help people a lot because many use `bower` to handle frontend plugins.

**Comment by suisho** [comment]
+1

**Comment by pepe** [comment]
+1

**Comment by michaelvillar** [comment]
Will definitely do that

**Comment by RivalNick** [comment]
:+1:

**Comment by michaelvillar** [comment]
It is now at `bower install dynamics.js`

**Comment by pepe** [comment]
vow, that was quick! Thanks
